      ! ==================================================================
      ! MPI Fortran Polyglot Stub Header (ABI Compliant)
      ! ==================================================================

      INTEGER MPI_SUCCESS, MPI_ERR_OTHER, MPI_ERR_UNKNOWN
      PARAMETER (MPI_SUCCESS=0, MPI_ERR_OTHER=16, MPI_ERR_UNKNOWN=14)

      INTEGER MPI_COMM_WORLD, MPI_COMM_SELF, MPI_COMM_NULL
      PARAMETER (MPI_COMM_NULL=256)
      PARAMETER (MPI_COMM_WORLD=257)
      PARAMETER (MPI_COMM_SELF=258)

      INTEGER MPI_DATATYPE_NULL, MPI_INT, MPI_DOUBLE_PRECISION
      INTEGER MPI_REAL, MPI_COMPLEX, MPI_DOUBLE_COMPLEX, MPI_LOGICAL
      INTEGER MPI_CHARACTER, MPI_BYTE, MPI_PACKED, MPI_2INT
      PARAMETER (MPI_DATATYPE_NULL=512)
      PARAMETER (MPI_INT=521)
      PARAMETER (MPI_REAL=538)
      PARAMETER (MPI_COMPLEX=539)
      PARAMETER (MPI_DOUBLE_PRECISION=540)
      PARAMETER (MPI_DOUBLE_COMPLEX=541)
      PARAMETER (MPI_LOGICAL=536)
      PARAMETER (MPI_CHARACTER=542)
      PARAMETER (MPI_BYTE=583)
      PARAMETER (MPI_PACKED=519)
      PARAMETER (MPI_2INT=555)

      INTEGER MPI_OP_NULL, MPI_SUM, MPI_MIN, MPI_MAX, MPI_PROD
      PARAMETER (MPI_OP_NULL=32)
      PARAMETER (MPI_SUM=33, MPI_MIN=34, MPI_MAX=35, MPI_PROD=36)

      INTEGER MPI_ANY_SOURCE, MPI_ANY_TAG, MPI_PROC_NULL
      PARAMETER (MPI_ANY_SOURCE=-1)
      PARAMETER (MPI_ANY_TAG=-2)
      PARAMETER (MPI_PROC_NULL=-3)

      INTEGER MPI_STATUS_SIZE
      PARAMETER (MPI_STATUS_SIZE=8)

      ! Sentinel memory addresses
      INTEGER MPI_BOTTOM, MPI_IN_PLACE
      COMMON /MPIPRIV/ MPI_BOTTOM, MPI_IN_PLACE